import Head from 'next/head';
import PathfindingVisualizer from '../components/PathfindingVisualizer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Zane&apos;s Pathfinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PathfindingVisualizer />
      </main>
    </>
  )
}
